### ISSUE TITLE
Adding fixture data

### ISSUE THREAD

**Issue by martijnbastiaan** [open-review/open-review#102]
In order to demo our site at the 7th of May, we need to fill the database with some initial data. This includes:
- Papers (preferably enough to trigger pagination)
- Reviews (about 5 reviews per paper, not all papers need reviews)
- Comments
- Votes on reviews
- ...?  

See PR https://github.com/open-review/open-review/pull/101 and branch `feature-more-fixtures`.

**Comment by thomasbrus** [comment]
Het zou leuk zijn als er ook bij de meeste pagina ook wat comments aanwezig zijn. (Als dat niet te veel moeite is :innocent:) Nu zijn er slechts 4 comments in totaal.

**Comment by thomasbrus** [comment]
Opgelost ondertussen.
