### ISSUE TITLE
MemcachedKeyCharacterError when having whitespaces in doc id

### ISSUE THREAD

**Issue by wietze** [open-review/open-review#103]
When using the document identifier feature for adding a review, trailing spaces may lead to MemcachedKeyCharacterError.

Steps to reproduce this issue:
1. Go to /reviews/add
2. Enter a document identifier with a trailing space, e.g. "1011.6435 "
3. Enter a review and submit

**Comment by shsdv** [comment]
Fixed it in two ways:
1. Trim the doc_id (apps/papers/scrapers.py:32)
2. Hash the MemcachedKey. This has multiple advantages (see apps/papers/scrapers.py:25-28)
