### ISSUE TITLE
Limit number of displayed authors

### ISSUE THREAD

**Issue by wietze** [open-review/open-review#105]
Some papers have a ridiculously high number of authors, such as _[arxiv:1403.5306](http://arxiv.org/abs/1403.5306)_. When adding such papers in OpenReview, the design of some pages gets ugly. 
Limiting the number of displayed authors (e.g. a maximum of 10, followed by 'et al') should fix this. 

![authors et al](https://cloud.githubusercontent.com/assets/2811785/2799266/447f9c40-cc5d-11e3-9e14-9b96f9de6dd4.png)

Pages affected:
/papers/{trending,new,controversial}
/papers/[id]/
/reviews/add

**Comment by thomasbrus** [comment]
:+1:

**Comment by thomasbrus** [comment]
Heb feature-dynamic-paper-information gemerged in base-design zodat de authors goed worden weergegeven. Zag dat er ook nog wat andere dingen in zaten (abstract weergeven), welke nog niet af zijn.
