### ISSUE TITLE
Bug in search functionality (?)

### ISSUE THREAD

**Issue by thomasbrus** [open-review/open-review#120]
This works: `http://localhost:8000/papers/search/?q=bitcoin`, but this doesn't: `http://localhost:8000/papers/search/?q=test`

> > NoReverseMatch at /papers/search/
> > Reverse for 'paper' with arguments '('',)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['papers/(?P<paper_id>\d+)/$']

**Comment by WNoort** [comment]
Not really a bug, but I have improved the query somewhat in 17920d72f1a492248e7d64453baffbb75ae3737b

**Comment by thomasbrus** [comment]
Oke, laten we het een feature noemen dan ;) Heb net weer even getest maar nu krijg ik altijd geen zoekresultaten. Heb elasticsearch wel runnen, doet ie het bij jou wel?

**Comment by WNoort** [comment]
even de database refreshen:

```
./manage.py rebuild_index
```

**Comment by thomasbrus** [comment]
Aah perfect, werkt nu:)
