### ISSUE TITLE
Voting button changes its color incorrectly

### ISSUE THREAD

**Issue by shsdv** [open-review/open-review#123]
When upvoting a review, the voting button becomes green. This is correct behaviour.
However, when clicking the downvoting-button once after having upvoted, the voting button becomes red. This is incorrect, because after up- and downvoting once, the result is a neutral vote ("+0"). Only after clicking the downvoting-button once more, the result is "-1" and the downvoting button should become red.

An alternative (better?) solution is to make a up-vote followed by a down-vote result in a down-vote (make the last vote count).

**Comment by martijnbastiaan** [comment]
> An alternative (better?) solution is to make a up-vote followed by a down-vote result in a down-vote (make the last vote count).

Implemented! This was already the case, but the counter forgot to substract 2 instead of 1 if a vote was followed by its opposite. Clicking a voted vote (hehehe) again results in a 'neutral' vote.
