### ISSUE TITLE
Fix test accounts.test.TestLoginView

### ISSUE THREAD

**Issue by WNoort** [open-review/open-review#128]
This test fails with the following error

```
ERROR: test_redirect (openreview.apps.accounts.tests.TestLoginView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/willem/code/open-review/openreview/apps/accounts/tests.py", line 73, in test_redirect
    self.assertTrue(response.url.endswith("/blaat"))
AttributeError: 'TemplateResponse' object has no attribute 'url'

```

Remember to document all affected code (including the test itself)!

Please create a branch from 'base-design' and don't merge before code is approved by Martijn (and possibly Thomas)

**Comment by martijnbastiaan** [comment]
Fixed in https://github.com/open-review/open-review/commit/3c366950d25fbf12bb592058f77277ba2ed62820.
