### ISSUE TITLE
Submitting a review while not logged in not handled well

### ISSUE THREAD

**Issue by wietze** [open-review/open-review#158]
When a user isn't logged in and visits a paper page, the 'Submit review' button is still enabled. Although a warning is shown when the user clicks on the textarea, the user can still write a review, give a star rating and and try to submit the review. After clicking the submit button, the 'please wait' animation shows up. After that, nothing happens. 

I think the desired behaviour is that the submit button is disabled when not logged in. Optionally, the textarea can be marked read-only and the visibility / rating options can be disabled.

**Comment by martijnbastiaan** [comment]
Fixed in https://github.com/open-review/open-review/commit/d14288f885df2de21bfc4f873e661bae1ae689fd and https://github.com/open-review/open-review/commit/5f5984f45ed7afaf50aaab7ce8bde3c79c27c9d7.
