### ISSUE TITLE
Domeinnaam

### ISSUE THREAD

**Issue by thomasbrus** [open-review/open-review#169]
Zoals besproken, zou het cool zijn om een domeinnaam te registreren waarop we OpenReview kunnen hosten. Eerder werd al 'mapitio.{org}' als mogelijke optie genoemd. Er zijn ook voorstanders voor het behouden van de naam 'open review'. Het probleem hier van is dat alle domeinnamen al geregistreerd zijn (openreview.org, open-review.org).

Anyway, wat denken jullie van [open-reviewing.org]()? Ook [openreviewing.org]() (zonder streepje) is nog niet bezet :smiley: Mooie hiervan is dat 'open review' in de naam terugkomt, en dat het ergens op slaat (_"doen jullie al aan open reviewing?"_)

ANdere ideeën zijn ook welkom!

/cc @basvandenbrink @martijnbastiaan @WNoort @shsdevries @wietze

**Comment by wietze** [comment]
Ik ben voor. Dit blijft het dichtst bij de naam die we al weken gebruiken en bovendien precies beschrijft wat we willen bereiken met ons platform.
