### ISSUE TITLE
Authors, keywords in paper-form

### ISSUE THREAD

**Issue by wietze** [open-review/open-review#17]
In branch paper-form is mijn deel voor de gegevens van een paper te vinden.
Mijn Django-skills zijn nog dermate beperkt, dat ik er niet in slaag om een authors/keywords veld daadwerkelijk op te laten slaan in de database, vanwege de manytomany-relatie. Misschien dat iemand anders daar naar kan kijken?
De rest werkt wel naar behoren.

**Comment by martijnbastiaan** [comment]
Geen probleem, ik zal er straks naar kijken (eerst even van mijn zondagavond genieten :-)).

**Comment by martijnbastiaan** [comment]
1. Many-to-many velden staan hier uitgebreid beschreven: https://docs.djangoproject.com/en/dev/topics/db/examples/many_to_many/. 
2. Omdat je een ModelForm gebruik hoef je veel velden niet meer te defineren. Dit geldt bijvoorbeeld voor author, publish_date, en urls. In de commit die hierna (edit: oke, dit wordt morgen :-)) volgt heb ik een paar velden verwijderd. Zie ook 3.
3. Ik raad sterke validatie van velden af: we willen bijvoorbeeld later doc id's als "arXiv:123.41" toestaan. Het nu al weigeren van die ids lijkt me geen goede zaak. (Representatie [het linken aan een externe bron] is een visualisatieprobleem, niet een van de database. Wat doen we bijvoorbeeld als arXiv uit de lucht gaat: hebben we dan alsnog illegale doc id's in de database?)
4. 'urls' was eerst een many-to-many field, maar dat heb ik geschrapt omdat we toch nooit willen zoeken op url's. Een extra tabel levert in dat geval alleen maar meer zorgen op, niet minder. Ik heb er daarom een TextField van gemaakt, waar mensen gewoon een lijst van urls kunnen dumpen. We kunnen dit bij het representeren alsnog omzetten naar klikbare links. 
5. Er zijn wat issues met add_review(): het voldoet niet aan ASIC. Het is bijvoorbeeld mogelijk dat p.is_valid() en not f.is_valid(), maar op p wordt dan ewl save() uitgevoerd. (En: er is geen schaamte in p en f uitschrijven naar paper_form en review_form.)
6. getters/setters worden in Python niet toegevoegd totdat ze nodig zijn (in tegenstelling tot Java). Het is helemaal geaccepteerd om gewoon form.paper = paper te doen. Later kan een property 'paper' worden gedefineerd met custom setters/getters.
7. Klein stijlfoutje: we springen in met 4 spaties, aldus PEP 8. 

Verder ziet het er goed uit. Ik snap dat Python/Django even wennen is :)

**Comment by martijnbastiaan** [comment]
Zie https://github.com/martijnbastiaan/open-review/commit/cfd4823b0021c656b350cacd40a7b1230851d243. Many to many velden werken nu min of meer (goed genoeg voor de versie van morgen), maar er moet nog wat aan de interface gebeuren.

Heb je nog vragen? Kan dit gemerged worden?

**Comment by wietze** [comment]
Ah top, je hebt er nog flink aan gesleuteld zie ik, thanks. Volgens mij is het verder in orde zo. Ook goed dat je die comentaren geeft, helpt inderdaad voor mij om het beter te snappen :)

**Comment by martijnbastiaan** [comment]
Ok! Branch gemerged!
