### ISSUE TITLE
Design main page

### ISSUE THREAD

**Issue by WNoort** [open-review/open-review#24]

**Comment by thomasbrus** [comment]
Heb controversial en new papers weggehaald. Deze kunnen wellicht op een andere pagina nog terugkomen. Om de nadruk wat meer te leggen op reviews (hier wordt Djoerd blij van), is er een **lijstje van top reviews toegevoegd**. Ook is de pagina nu wat rustiger.

![open review](https://f.cloud.github.com/assets/232034/2450093/23d30e40-aeb8-11e3-94e9-16822b88fff9.png)

Zie nu dat ie nog wel iets breder kan.. Deze week ga ik het design implementeren (alleen deze pagina).
