### ISSUE TITLE
Naive datetime

### ISSUE THREAD

**Issue by WNoort** [open-review/open-review#31]
While running tests and the testserver the following warning keeps occuring:

/usr/local/lib/python3.3/dist-packages/django/db/models/fields/**init**.py:903: RuntimeWarning: DateTimeField Review.timestamp received a naive datetime (2014-03-06 20:23:04.259617) while time zone support is active.
  RuntimeWarning)

**Comment by martijnbastiaan** [comment]
This is a duplicate of issue #18.
