### ISSUE TITLE
Travis CI duurt lang

### ISSUE THREAD

**Issue by thomasbrus** [open-review/open-review#43]
Het duurt op Travis ongeveer 14 minuten om de test suite te draaien (ongeacht of ie slaagt).

**Comment by martijnbastiaan** [comment]
Nou, eerder 7 minuten. Er wordt namelijk in twee environments getest, die parallel worden uitgevoerd. De duur het uitvoeren van de daadwerkelijke tests ~100 seconden, de rest is dependencies installeren..

Hopelijk kunnen we als Ubuntu 14.04 uit is (en Travis over is?) veel dependencies uit APT halen i.p.v. PyPi, dat zou al veel moeten schelen. Heb je nog verdere ideeen?

**Comment by martijnbastiaan** [comment]
Het lijkt erop dat Travis inderdaad gaat upgraden: https://github.com/travis-ci/travis-ci/issues/2046

**Comment by thomasbrus** [comment]
Oke dat zou mss helpen.. Het lijkt trouwens toch wel 14 minuten te duren voordat ie helemaal klaar is, dat staat ook bij _duration_. (En ze worden niet parallel uitgevoerd zag ik net, alleen in de betaalde versie mss (?))

**Comment by martijnbastiaan** [comment]
Hmm, ik denk dat het gewoon een kwestie van kans is. Ik heb ze al een paar keer parallel zien uitvoeren. Maar ik denk dat ik de environment DEBUG=1 eruit ga gooien, want ik kwam er net achter dat `manage.py test` DEBUG=0 afdwingt.. :|

(Ik hoopte te bereiken dat coveralls ook dingen onder `if DEBUG` zou meerekenen - toen dat niet gebeurde nam ik aan dat het aan coveralls lag.)

**Comment by WNoort** [comment]
Haha! Das wel zonde van je tijd geweest dan
