### ISSUE TITLE
Travis CI faalt voor meerdere branches

### ISSUE THREAD

**Issue by thomasbrus** [open-review/open-review#44]
In een aantal branches (`star-ratings`, `remove-beautiful-soup`, etc) die vandaag gepusht zijn (en volgens mij up to date zijn met master), faalt Travis CI met meldingen als: "broken pipe" "address already in use", "no such process", enzovoort.

**Comment by thomasbrus** [comment]
Ik ook niet, het gebeurt ook alleen op Travis. Zie hier bijv:

https://travis-ci.org/open-review/open-review/jobs/21508988#L1076 
https://travis-ci.org/open-review/open-review/jobs/21533943#L1022
https://travis-ci.org/open-review/open-review/jobs/21520378#L862

**Comment by WNoort** [comment]
It seems good practice to me to push my progression every half hour or so (never have your source in a single place!). If this means that the tests fail, so be it as long as this happens in my own branch.

**Comment by WNoort** [comment]
And yes. Simon totally screwed up the tests :) Same for you.

**Comment by thomasbrus** [comment]
Hmmm ok.

Enig idee wat hier mis gaat bijvoorbeeld: https://travis-ci.org/open-review/open-review/jobs/21524033#L793? Het niet duidelijk wat de fout is (zal wel iets heel simpels zijn), behalve dat er een ConnectionRefusedError optreed.

**Comment by martijnbastiaan** [comment]
> It seems good practice to me to push my progression every half hour or so (never have your source in a single place!). If this means that the tests fail, so be it as long as this happens in my own branch.

That's OK indeed as long as you squash your commit messages to meaningful units before merging with master. However, I don't think that's what Thomas is getting at. See:

`ConnectionRefusedError: [Errno 111] Connection refused`

It seems these issues are not reproducible locally, but keep turning up on Travis.

**Comment by WNoort** [comment]
I can see what you mean now:
https://travis-ci.org/open-review/open-review/builds/21537321

**Comment by martijnbastiaan** [comment]
@WNoort That build fails on "RuntimeError: maximum recursion depth exceeded". Broken pipes usually mean Firefox is closed before a request was completely served by the testserver running in the background; which is OK (ugly anyway, but not wrong).

**Comment by martijnbastiaan** [comment]
@thomasbrus I found the issue (I think): the testserver returns a HTTP 500 which results in such an obscure error message. The 500 seems to be generated by: `/review/add`. On a local server it get:

```
TemplateSyntaxError at /review/add

Invalid filter: 'bootstrap'
```

And:

``` bash
martijn@deskei:~/code/open-review$ grep "bootstrap" -r *
openreview/apps/main/templates/main/add_review.html:           {{ add_paper_form|bootstrap }}
```

**Comment by martijnbastiaan** [comment]
Woops, I accidentally closed the issue..

**Comment by martijnbastiaan** [comment]
Ah, and I discovered the underlying issue: somehow the merge went wrong. See add_review.html:

https://github.com/open-review/open-review/blob/landing-page-design/openreview/apps/main/templates/main/add_review.html

Is it OK with you if I do the following:
1. Revert 4ef12080818c53ca331fe6809aa1fa63b2c5c672.
2. Fix wrong merge
3. Force push

?

**Comment by thomasbrus** [comment]
Dat is het inderdaad, zie het nu ook:) Heb zojuist al ge-revert, en merge conflicts verwijderd (https://github.com/open-review/open-review/pull/39)

**Comment by martijnbastiaan** [comment]
Nice ^^. Issue closed?

**Comment by martijnbastiaan** [comment]
Oh btw: de oude scraper code veroorzaakt van tijd tot tijd gekke fouten. Mergen met master zou dit moeten oplossen.

**Comment by thomasbrus** [comment]
Het lijkt opgelost (#39)
