### ISSUE TITLE
Split scraper into scraper + controller

### ISSUE THREAD

**Issue by martijnbastiaan** [open-review/open-review#50]
The arXiv scraper does essentially three things:
- Caching
- Error handling
- Scraping

Obviously the first two things don't _really_ belong to the scraper code, but is something which should be done for each scraper. Since we cannot reasonably solve this using inheritance (base class would have to look 'down' instead of 'up'), I propose splitting the current model in two:

``` python
class ScraperError(Exception):
    pass

class Controller:
    def __init__(self, scraper):
        self.scraper = scraper

    def run(self, doc_id):
        url = self.scraper.get_url(doc_id)

        try:
            doc = self.scraper.get_doc(url)
        except Exception:
            raise ScraperError("An exception occurred while fetching {doc_id}".format(**locals())

        try:
            return dict(self.scraper.parse(doc))
        except Exception:
            raise ScraperError("An exception occurred while parsing {doc_id}".format(**locals()))

class Scraper:
    url = None
    parser = lxml.html.parse
    publisher = None

    @classmethod
    def get_url(cls, doc_id):
        return cls.url.format(doc_id=doc_id)

    @classmethod
    def get_doc(cls, url):
        return self.parser(urllib.open(url))

    @classmethod
    def parse(cls):
        raise NotImplemented
```

I'm not really sure about the classmethods, but you get the idea. This would reduce the arXiv scraper to:

``` python
class ArXivScraper(Scraper):
    url = "http://arxiv.org/abs/{doc_id}"
    publisher = "ArXiv"

    @classmethod
    def parse(cls, doc):
        yield "title", doc.cssselect("entry title")[0].text
        yield "authors", [x.text for x in doc.cssselect("entry author name")]
        yield "publish_date", datetime.strptime(doc.cssselect("entry published")[0].text, "%Y-%m-%dT%H:%M:%SZ")
```

**Comment by WNoort** [comment]
I am also not sure about the classmethods. The ArXiv scraper is quite simple, but a DOI scraper would be way more complex.

I would also take this opportunity to be more specific about the Exceptions. For example HTTPError and LxmlError. This would make debugging much simpler in future.

Caching has disappeared, which is necessary for decent performance.

The usage of the scraper library would then be as follows:

``` python
import openreview.apps.papers.scrapers as scrapers
try:
    p = scrapers.Controller(scrapers.ArXivScraper()).run("1403.2443")
except scrapers.ScraperError:
    pass

```

**Comment by martijnbastiaan** [comment]
Wouldn't a DOI scraper be equivalent to running a lot of scrapers in parallel until one finds it on their domain? 

More specific exceptions would be great indeed. I wouldn't call them `{HTTP,Lxml}Error` though as it ties too much to one particular technology. Maybe `FetchError(ScraperError)` and `ParseError(ScraperError)`?

Anyway, let me know (if you want to) if/when you start to implement these kind of changes. Maybe we can work it out together.

PS: Are you familiar with the `from ... import ...` syntax? The import statement could be reduced to:

``` python
from openreview.apps.papers import scrapers
```

`as` is mostly used as a 'renamer'. For example:

``` python
from openreview.apps.papers import scrapers as s
```

**Comment by WNoort** [comment]
Almost finished this. Your suggestions are great for tasting the git rebase functionality :)
See branch enhancement-scraper-functionality-split

**Comment by WNoort** [comment]
I would suggest to define the default fetching and parsing error in Scraper like this:

``` python
class Scraper:
 fetching_errors = HTTPError
 parsing_errors = (lxml.etree.LxmlError, IndexError)
```

This sets a right default value, and allows overriding by specific scrapers
