### ISSUE TITLE
Difference {base,splash}.html

### ISSUE THREAD

**Issue by martijnbastiaan** [open-review/open-review#53]
Hi Thomas,

What's the difference between base.html and splash.html? Most templates inherit from the first one, but landing_page.html doesn't although I don't see a difference between the two. Which one should we use?

**Comment by thomasbrus** [comment]
You should use base.html. The difference is/will be in the header. Splash.html has a large header and no navigation, base.html will have a small header and a menu/navigation. (This is especially convenient since splash.css has styles for `body > header`, etc..)
