### ISSUE TITLE
MathJax should fallback (i.e., not render) if it detects illegally formatted strings

### ISSUE THREAD

**Issue by martijnbastiaan** [open-review/open-review#63]
See https://github.com/open-review/open-review/issues/62. We should not render illegally formatted text.

**Comment by shsdv** [comment]
The noError extension should fix this - see http://docs.mathjax.org/en/latest/tex.html#noerrors. This extension is used on arXiv too.

"The noErrors extension prevents TeX error messages from being displayed and shows the original TeX code instead."

Unfortunately I was unable to get this working.
