### ISSUE TITLE
Minor homepage issues

### ISSUE THREAD

**Issue by shsdv** [open-review/open-review#64]
There are two small issues with the box indicating the number of reviews on the homepage:
1. The box only expands to "{{n}} reviews" when the user hovers over the link, not over the whole line
2. If the length of the title of a paper is too long, the line will be split over two lines when the box is expanded

**Comment by thomasbrus** [comment]
Yes I noticed these issues as well,
1. First one can be fixed easily, we'll just have to change the markup/css a bit
2. The title is trimmed down to a maximum of 60 chars, so this issue should not occur. If it still does we may need to decrease it to 50 chars for example.
