### ISSUE TITLE
Frontpage design doesn't scale to mobile devices

### ISSUE THREAD

**Issue by martijnbastiaan** [open-review/open-review#65]
I have a Samsung Galaxy S with a display resolution of 480x800 (HVGA) with which I can't view the frontpage in a convenient manner. Issues:
- When loading the frontpage, it is displayed wholly causing it to not be readable. I have to zoom in to read, leaving elements to be partially cut off.
- There is no convenient manner to find out what the little 'X reviews' boxes mean. I have to either:
  - "Hold" the link for a while, causing my browser to display an 'open url?' page. After backing up, the link is marked as 'hovered'.
  - Click on the link, causing it to be in the hovered state momentarily but also redirecting my browser (of course).
- An enormous amount of white space is displayed at the bottom of the screen, which makes scrolling when zoomed in confusing (as you might end up with a white page).
- I expected the {trending,top} boxes to be stacked vertically, instead of horizontally.

Firefox OS does it a little bit better by wrapping the header, but it still triggers awkward behaviour when scrolling.

![schermafbeelding 2014-04-04 om 09 42 35](https://cloud.githubusercontent.com/assets/5658854/2588442/6b5f49bc-ba3a-11e3-81bb-ff98744188d8.png)

**Comment by thomasbrus** [comment]
Will look at this in the future, but I don't think it has high priority right now.
