### ISSUE TITLE
Installation instructions for Elasticsearch

### ISSUE THREAD

**Issue by WNoort** [open-review/open-review#66]
The first time I installed elasticsearch, the installer suggested some commands to automatically start elasticsearch on startup. The second time it didn't. Can someone check the wiki and add the missing command?

Furthermore, I haven't tested the installation instructions for Fedora-like operating systems. Can someone verify these instructions?

**Comment by shsdv** [comment]
The missing command is:

```
sudo update-rc.d elasticsearch defaults 95 10
```

I've added it to the Wiki, closing this issue now.

**Comment by WNoort** [comment]
Reopening. Still need an answer to the second part of the question :)

**Comment by martijnbastiaan** [comment]
Btw, you can always run `dpkg-reconfigure <package>` in order to run the initial setup again.

**Comment by basvandenbrink** [comment]
Done.
