### ISSUE TITLE
Rating (raty?) widgets shows twice

### ISSUE THREAD

**Issue by martijnbastiaan** [open-review/open-review#73]
BLOCKS: Release 0.12

_Reproduce_:
1. Navigate to http://localhost:8000/review/add
2. Select 'manually'
3. Click textarea 'authors'
4. Press key, for example 'a'.

_What do you expect to happen?_ For it (star ratings) to NOT show up twice
_What happens instead?_ Star rating shows twice

This actually breaks unittests (^^) when merging with `feature-categories`. See:
1. `python3 manage.py test openreview.apps.main.tests.reviewform.TestReviewFormLive`
2. https://travis-ci.org/open-review/open-review/builds/22451602

I've put in a sleep statement to make it more obvious while testing. Relevant test output:

``` ======================================================================
ERROR: test_paper_gets_committed (openreview.apps.main.tests.reviewform.TestReviewFormLive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/martijn/code/open-review/openreview/apps/main/tests/reviewform.py", line 183, in test_paper_gets_committed
    for option in catlist.find_elements_by_tag_name('option'):
AttributeError: 'list' object has no attribute 'find_elements_by_tag_name'

----------------------------------------------------------------------
Ran 1 test in 10.342s
```

It seems to have something to do with MathJax as my browser immediately starts loading mathjax after the stars show up a second time.

**Comment by shsdv** [comment]
Actually, not just the star ratings are shown twice, the whole page is shown twice...
I'm investigating this further.

**Comment by martijnbastiaan** [comment]
Ah, strange! Thanks! :)

**Comment by shsdv** [comment]
After pulling the latest changes from Git (and updating submodules etc.), I can't load any page anymore. The following error appears:

```
UncompressableFileError at /
'bower_components/jquery/jquery.js' could not be found in the COMPRESS_ROOT '/home/simon/code/openreview/open-review/collected_static' or with staticfiles.
```

**Comment by martijnbastiaan** [comment]
Sorry, I should have mailed everyone. We're using Bower to manage jquery
(and maybe other dependecies in the feature).

sudo apt-get install nodejs npm
npm install -g bower
cd /static/
bower install
Op 7 apr. 2014 17:24 schreef "shsdevries" notifications@github.com het
volgende:

**Comment by shsdv** [comment]
Okay, got the server working now.
BTW, running `bower install` resulted in `/usr/bin/env: node: No such file or directory`. This was fixed by running:

```
ln -s /usr/bin/nodejs /usr/bin/node
```

**Comment by shsdv** [comment]
Although it is fixed now, I am not entirely satisfied yet. Currently, the preview url in apps/main/templates/main/add_review.html is hard-coded to `/papers/-1/preview`. I tried to solve this using the `{% url ... %}` construct, but this didn't work because `papers/-1/preview` is in another app. I don't know how to link to a page in another app - I've read about using "app_name:page", but that didn't seem to work. Do you know a better way, @martijnbastiaan?

**Comment by martijnbastiaan** [comment]
I don't think it matters whether or not it is in another app, but I don't think it's allowed to use the same name parameter (in urls) twice. I did use this construct in `papers/urls.py`:

`url(r'^(?P<paper_id>\d+)/review/(?P<review_id>\-?\d+)$', ReviewView.as_view(), name="review"),`

This allows 'review_id' to be '-1', which the view checks. (On further thought, I still dislike this idea. We really need to build a well-defined API.. oh well).

Anyway, I think the fix fails to address the underlying issue: both the html elements of 'preview' and 'paper-form' have a class `new` on them, which `writing.coffee` acts upon. A better fix (IMO, of course) would be:

``` diff
diff --git a/openreview/apps/papers/static/papers/writing.coffee b/openreview/apps/papers/static/papers/writing.coffee
index 66edee4..238daf1 100644
--- a/openreview/apps/papers/static/papers/writing.coffee
+++ b/openreview/apps/papers/static/papers/writing.coffee
@@ -74,7 +74,7 @@ icon_clicked = (hide, toggle) ->

 $(".review .options .edit").click(icon_clicked("new", "edit"))
 $(".review .options .reply").click(icon_clicked("edit", "new"))
-$(".new:visible textarea").focus(->
+$(".new-review:visible textarea").focus(->
   init_writing($(this).closest(".new"))
 )

diff --git a/openreview/apps/papers/templates/papers/paper.html b/openreview/apps/papers/templates/papers/paper.html
index 81ab8c3..51676bc 100644
--- a/openreview/apps/papers/templates/papers/paper.html
+++ b/openreview/apps/papers/templates/papers/paper.html
@@ -65,7 +65,7 @@
     <hr/>

     {% if not user.is_anonymous %}
-    <form method="post" class="new" data-preview="{% url 'preview' paper.id %}">
+    <form method="post" class="new new-review" data-preview="{% url 'preview' paper.id %}">
         {% csrf_token %}
         <table>{{ add_review_form }}</table>
         <br /><input name="add_review" type="submit" value="Submit review">

```

Do you agree that this is a better solution? If so, I will implement it.

**Comment by shsdv** [comment]
I agree that the fix in commit 5aeaf08 is not the best way to solve this. However, your solution does not take into account that one can preview both a comment and a review. Note that when editing a comment (which is a bit difficult to test at the moment, because the edit-button became invisible in commit 8fbfc63), a preview is also shown. I don't know if it is necessary to distinguish between comments and reviews for the preview, since in both cases you only want to preview the markdown. Maybe we should create a generic "preview" page? For rendering markdown, it doesn't matter whether the text is a comment or a review.

(And yes, I like the idea of an API - but that probably is something to discuss next time :))

**Comment by martijnbastiaan** [comment]
> However, your solution does not take into account that one can preview both a comment and a review.

It only acts upon the 'new review' at the 'paper' page. I should have commented this in writing.coffee. This code:

``` coffeescript
$(".review .options .edit").click(icon_clicked("new", "edit"))
$(".review .options .reply").click(icon_clicked("edit", "new"))
```

Initialises the preview part if edit/new is clicked. The difference is that the preview box at the paper page should be shown after the user focusses the textarea (which is immediately shown after loading), but the comment/edit should not.

To clarify, this code:

``` coffeescript
$(".new-review:visible textarea").focus(->
  init_writing($(this).closest(".new"))
)
```

Is the relevant code for non-edit/non-comment previews. (Or maybe I don't get it :P. Please explain if so.)

> Maybe we should create a generic "preview" page? 

+1

**Comment by shsdv** [comment]
Ah right, I forgot that writing.coffee already contains code for showing previews based on clicking the new/edit buttons. In that case, I agree this is a better solution.
