### ISSUE TITLE
Django error-html wordt niet toegevoegd

### ISSUE THREAD

**Issue by thomasbrus** [open-review/open-review#81]
Heb de volgende wijziging gemaakt in login.html: https://github.com/open-review/open-review/compare/5269906...base-design#diff-1. Op een of andere manier wordt de error html (`<ul class="errorlist">` etc.) niet meer toegevoegd. Wat zie ik over het hoofd?

**Comment by martijnbastiaan** [comment]
Ik denk dat ik 'm zie :)

**apps/accounts/views.py:25**

``` python
register_data = self.request.POST if "new" in self.request.POST else None
login_data = self.request.POST if "existing" in self.request.POST else None
```

Oftewel: hij kijkt naar de `<input type="submit" name="X">` dingen. Of werkt dat met ID's?

**Comment by thomasbrus** [comment]
Oke bedankt. Dat was het inderdaad. Heb nu een nieuw probleem, namelijk dat 't me niet lukt om de form html aan te passen, maar dat kan nog wel even wachten
