### ISSUE TITLE
"Flash notice" laten zien bij redirect naar login page

### ISSUE THREAD

**Issue by thomasbrus** [open-review/open-review#82]
Gebruikers worden nu (zonder uitleg) doorgestuurd naar de inlogpagina als ze naar een pagina willen gaan waarvoor je ingelogd moet zijn.

In Rails is het gebruikelijk om dan een flash notice te tonen die eenmalig wordt weergeven aan het begin van de (inlog)pagina. Daarin staat dan bijv iets als: "Om je instellingen te wijzigen dien je eerst in te loggen."

**Comment by martijnbastiaan** [comment]
Yes, dat moet veranderen. Ter referentie:

https://docs.djangoproject.com/en/dev/ref/contrib/messages/
