### ISSUE TITLE
Paper page: Abstract weergeven

### ISSUE THREAD

**Issue by WNoort** [open-review/open-review#85]
Each alinea in a `<p>` tag, truncate when much longer than right panel.

**Comment by thomasbrus** [comment]
Should not be closed yet, cause a) content is not truncated, and b) the whole content is now always in one `<p>`. Also, line breaks are not displayed at all. See here for example:

![schermafbeelding 2014-04-30 om 23 07 58](https://cloud.githubusercontent.com/assets/232034/2847194/891df656-d0ab-11e3-8995-f895e577c81c.png)

**Comment by thomasbrus** [comment]
Fixed by Wietze (8a87797c7e28e8bc02cb23b4d98371de1d6ed63d). Still won't show linebreaks but thats fine for now

**Comment by thomasbrus** [comment]
Als ik naar http://localhost:8000/papers/25/ ga, zie ik dit:

![schermafbeelding 2014-05-07 om 14 08 59](https://cloud.githubusercontent.com/assets/232034/2902113/8c64acee-d5e0-11e3-8e2e-6503dcd5fb43.png)

Die readmore link zou niet zichtbaar moeten zijn, en hij zou inline achter de paragraph moeten komen, tenminste, zo werkt het als de abstract _wel_ overflowed
