### ISSUE TITLE
Paper page: display user's name + title + university

### ISSUE THREAD

**Issue by WNoort** [open-review/open-review#90]
- [x] Add option to specify university and title in account/settings
- [x] Take into account different scenarios:
  - Anonymous reviews
  - Name not specified
  - University not specified
  - ...

**Comment by WNoort** [comment]
Fixed in bc4cc85ceaa60f893f3394493b36cf6da5a65620

**Comment by WNoort** [comment]
Merged in c7638137729fd14f60e92519cd4d5590a8280079
Closing...

**Comment by thomasbrus** [comment]
![schermafbeelding 2014-05-02 om 18 48 44](https://cloud.githubusercontent.com/assets/232034/2865190/ad666678-d219-11e3-9061-c391cbea1da6.png)

Please note the `{}`. Bug?

**Comment by thomasbrus** [comment]
Fixed by d015d19c194bb28f3694055a31eb735283c4e104
